'use client'

import { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'
import { useState } from 'react'

export default function DownloadReportButton({ 
  reportRefId, 
  patientName = "Unknown Patient", 
  scanId = "000" 
}: { 
  reportRefId: string,
  patientName?: string,
  scanId?: string 
}) {
  const [isGenerating, setIsGenerating] = useState(false)

  const generatePDF = async () => {
    const element = document.getElementById(reportRefId)
    if (!element) {
      alert('Report content not found!')
      return
    }

    setIsGenerating(true)

    try {
      // 1. Capture the DOM element as a canvas
      const canvas = await html2canvas(element, {
        scale: 2, // High resolution
        useCORS: true, // Allow loading external images
        logging: false
      })

      // 2. Calculate PDF dimensions
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      })

      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = pdf.internal.pageSize.getHeight()
      const imgWidth = pdfWidth - 20 // 10mm margin on each side
      const imgHeight = (canvas.height * imgWidth) / canvas.width

      // 3. Add Header Text
      pdf.setFontSize(18)
      pdf.text('Dental AI Analysis Report', 10, 15)
      
      pdf.setFontSize(12)
      pdf.text(`Patient: ${patientName}`, 10, 25)
      pdf.text(`Scan ID: #${scanId}`, 10, 32)
      pdf.text(`Date: ${new Date().toLocaleDateString()}`, 10, 39)

      // 4. Add the captured image
      pdf.addImage(imgData, 'PNG', 10, 45, imgWidth, imgHeight)

      // 5. Footer
      pdf.setFontSize(10)
      pdf.text('Generated by DentalAI System', 10, pdfHeight - 10)

      // 6. Save
      pdf.save(`DentalReport_${scanId}.pdf`)

    } catch (error) {
      console.error('PDF Generation Error:', error)
      alert('Failed to generate PDF. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <button 
      onClick={generatePDF}
      disabled={isGenerating}
      className={`bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition-colors flex items-center gap-2 ${isGenerating ? 'opacity-75 cursor-wait' : ''}`}
    >
      {isGenerating ? (
        <>
          <span className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full"></span>
          Generating...
        </>
      ) : (
        <>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>
          Download Report
        </>
      )}
    </button>
  )
}
